# 将本文件复制一份命名为“database.secret.yml”，并补充 MySQL 数据密码
# 需要实现创建好数据库 agri_analysis

development:
  database:
    drivername: mysql+pymysql
    jdbc: jdbc:mysql
    username: dsj
    password: Dsj@2023
    host: 117.50.181.190
    port: 3306
    database: agri_analysis
